import type { Metadata } from "next";
import "./globals.css";

import { DM_Sans } from "next/font/google";
import { twMerge } from "tailwind-merge";
const font = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={twMerge([font.className, "bg-gray-50"])}>
        {children}
      </body>
    </html>
  );
}
